256colors
dom96/nimbox pull request #4
Opened 2018-06-20 13:26 UTC by jonathanabennett

This is a simple start to fixing the 256 colors support issue raise in #2. It needs error correction and, since I have only been programming in Nim for a week, I'm still not sure of the best way to do that. But hopefully this code moves us toward 256 color support. I have tested it naively with several different color codes and it has worked successfully.

2018-06-21 21:40 UTC, dom96 requested changes
Thank you for this.

It seems you've sadly included the changes from the other PR in this one too.

2018-06-21 21:40 UTC, dom96 commented on nimbox.nim
> +               fg: int, bg: int, style: T) =
Would be nice to use the ``Color`` type from the stdlib ``colors`` module here, sucks that it clashes with the ``Color`` type defined in this module though :/

2018-06-26 08:50 UTC, jonathanabennett commented
Is there an easy way to back out the other commit? I'm still fairly new to git and forgot to checkout back to the master branch before creating this branch.

2018-06-26 09:32 UTC, dom96 commented
Might be easiest to just re-do the PR

2018-07-06 03:54 UTC, closed without merging